<?xml version="1.0" encoding="UTF-8"?>
<!-- gematik revision="\main\rel_online\rel_ors1\6" -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:GERROR="http://ws.gematik.de/tel/error/v2.0"    xmlns:KSR="http://ws.gematik.de/ksr/v1.1" xmlns:KSRW="http://ws.gematik.de/ksr/WSDL/v1.1" targetNamespace="http://ws.gematik.de/ksr/WSDL/v1.1">
    <documentation>
		Copyright (c) 2014, gematik - Gesellschaft für Telematikanwendungen der Gesundheitskarte mbH. Alle Rechte vorbehalten.
		Beschreibung: Dienst Verteilung von Firmware dezentraler Komponenten
		version=1.1.0
	</documentation>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import schemaLocation="Konfigurationsdienst.xsd" namespace="http://ws.gematik.de/ksr/v1.1"/>
			<import schemaLocation="../tel/error/TelematikError.xsd" namespace="http://ws.gematik.de/tel/error/v2.0"/>
        </schema>
    </types>
    <message name="listUpdatesRequestMessage">
        <part name="parameter" element="KSR:listUpdatesRequest"/>
    </message>
    <message name="listUpdatesResponseMessage">
        <part name="parameter" element="KSR:listUpdatesResponse"/>
    </message>
	<message name="FaultMessage">
		<part name="parameter" element="GERROR:Error"/>
	</message>
    <portType name="KonfigurationsdienstPortType">
        <operation name="list_Updates">
            <input message="KSRW:listUpdatesRequestMessage"/>
            <output message="KSRW:listUpdatesResponseMessage"/>
			<fault name="FaultMessage" message="KSRW:FaultMessage"/>
        </operation>
    </portType>
    <binding name="KonfigurationsdienstBinding" type="KSRW:KonfigurationsdienstPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="list_Updates">
            <soap:operation soapAction="http://ws.gematik.de/ksr/v1.1#ListUpdates"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="FaultMessage">
				<soap:fault name="FaultMessage" use="literal"/>
			</fault>
        </operation>
    </binding>
    <service name="Konfigurationsdienst">
        <port name="KonfigurationsdienstPort" binding="KSRW:KonfigurationsdienstBinding">
            <soap:address location="http://example.com"/>
        </port>
    </service>
</definitions>
