<?xml version="1.0" encoding="UTF-8"?>
<!-- ===================================================================== -->
<!-- 	                    Copyright (C) 2022 gematik GmbH. Alle Rechte vorbehalten.                                 -->
<!-- ===================================================================== -->
<!-- Version History			
            version: V1.0.0
			===============
            *** Revision 18.11.2022
                targetNamespace für WSDL und Namespace-Präfixes angepasst
			*** initial 13.09.2022
	 End of Version History-->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:GERROR="http://ws.gematik.de/tel/error/v2.0" xmlns:POPP="http://ws.gematik.de/conn/popp/PoPPService/v1.0" xmlns:POPPW="http://ws.gematik.de/conn/popp/PoPPService/WSDL/v1.0" targetNamespace="http://ws.gematik.de/conn/popp/PoPPService/WSDL/v1.0">
    <documentation>
		Copyright (c) 2022, gematik GmbH. Alle Rechte vorbehalten.
		Beschreibung: Dienst zum Erzeugen eines Anwesenheitsnachweises
		version=1.0.0
	</documentation>
    <types>
        <xs:schema>
            <xs:import schemaLocation="PoPPService.xsd" namespace="http://ws.gematik.de/conn/popp/PoPPService/v1.0"/>
            <xs:import schemaLocation="../../tel/error/TelematikError.xsd" namespace="http://ws.gematik.de/tel/error/v2.0"/>
        </xs:schema>
    </types>
    <message name="PerformPoPPRequestMessage">
        <part name="parameter" element="POPP:PerformPoPP"/>
    </message>
    <message name="PerformPoPPResponseMessage">
        <part name="parameter" element="POPP:PerformPoPPResponse"/>
    </message>
    <message name="FaultMessage">
        <part name="parameter" element="GERROR:Error"/>
    </message>
    <portType name="PoPPServicePortType">
        <operation name="PerformPoPP">
            <input message="POPPW:PerformPoPPRequestMessage"/>
            <output message="POPPW:PerformPoPPResponseMessage"/>
            <fault name="FaultMessage" message="POPPW:FaultMessage"/>
        </operation>
    </portType>
    <binding name="PoPPServiceBinding" type="POPPW:PoPPServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="PerformPoPP">
            <soap:operation soapAction="http://ws.gematik.de/conn/popp/PoPPService/v1.0#PerformPoPP"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="FaultMessage">
                <soap:fault name="FaultMessage" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="PoPPService">
        <port name="PoPPServicePort" binding="POPPW:PoPPServiceBinding">
            <soap:address location="http://unspecified"/>
        </port>
    </service>
</definitions>
