<?xml version="1.0" encoding="UTF-8"?>
<!-- Version History      
           version: V7.4.1
			===========
			*** neuer erlaubter Wert für ECDSA-Signatur in Aufrufparameter SIG:Optional Inputs/dss:SignatureType
            version: V7.4.0
			===========
			*** Abgetrennt als AuthSignatureService von SignatureService 7.3      
            version: V7.3.0
			===========
			*** SignatureService updated von 7.2 auf 7.3
            version: V7.2.0
			===========
			*** SignatureService updated von 7.1 auf 7.2
            version: V7.1.0
			===========
			*** SignatureService updated von 7.0 auf 7.1
	 End of Version History-->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:SIG="http://ws.gematik.de/conn/SignatureService/v7.4" xmlns:SIGW="http://ws.gematik.de/conn/AuthSignatureService/WSDL/v7.4" xmlns:CCTX="http://ws.gematik.de/conn/ConnectorContext/v2.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:GERROR="http://ws.gematik.de/tel/error/v2.0" targetNamespace="http://ws.gematik.de/conn/AuthSignatureService/WSDL/v7.4">
	<documentation>
		Copyright (c) 2020, gematik GmbH. Alle Rechte vorbehalten.
		Beschreibung: Konnektor Signatur Basisanwendung Authentifizierung
		version=7.4.1 
	</documentation>
	<types>
		<xs:schema>
			<xs:import schemaLocation="SignatureService.xsd" namespace="http://ws.gematik.de/conn/SignatureService/v7.4"/>
			<xs:import schemaLocation="ConnectorContext.xsd" namespace="http://ws.gematik.de/conn/ConnectorContext/v2.0"/>
			<xs:import schemaLocation="../tel/error/TelematikError.xsd" namespace="http://ws.gematik.de/tel/error/v2.0"/>
		</xs:schema>
	</types>
	<message name="ExternalAuthenticateRequestMessage">
		<part name="parameter" element="SIG:ExternalAuthenticate"/>
	</message>
	<message name="ExternalAuthenticateResponseMessage">
		<part name="parameter" element="SIG:ExternalAuthenticateResponse"/>
	</message>
	<message name="FaultMessage">
		<part name="parameter" element="GERROR:Error"/>
	</message>
	<portType name="AuthSignatureServicePortType">
		<operation name="ExternalAuthenticate">
			<input message="SIGW:ExternalAuthenticateRequestMessage"/>
			<output message="SIGW:ExternalAuthenticateResponseMessage"/>
			<fault name="FaultMessage" message="SIGW:FaultMessage"/>
		</operation>
	</portType>
	<binding name="AuthSignatureServiceBinding" type="SIGW:AuthSignatureServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="ExternalAuthenticate">
			<soap:operation soapAction="http://ws.gematik.de/conn/SignatureService/v7.4#ExternalAuthenticate"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="FaultMessage">
				<soap:fault name="FaultMessage" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="AuthSignatureService">
		<port name="AuthSignatureServicePort" binding="SIGW:AuthSignatureServiceBinding">
			<soap:address location="http://ti-konnektor/authsignatureservice"/>
		</port>
	</service>
</definitions>
